### ISSUE TITLE
QA: /events/2023-zelta-user-conference

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#182]
This is the 'new' event page layout.

- https://main--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference
- https://www.figma.com/file/FGFCs3L8fWfh7AnGUCi0RG/Marketo-Form-Landing-Page?node-id=2038-16024&t=0MXUH5mwEzgXe75p-0

**Comment by arumsey** [comment]
@sachinmesh ready for review

**Comment by keith-kaplan** [comment]
Helping out with QA'ing this page until @sachinmesh can jump in...
This font size needs to be 21px
<img width="875" alt="image" src="https://user-images.githubusercontent.com/111377779/234387053-5f68ce00-4089-4aef-987a-d20fe43da99e.png">

Spacing between these blocks should be 96px
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/111377779/234387635-32d57c5b-df18-45fe-82ae-b4a861287dc1.png">

Accordion block is not supposed to span full width. It's suppose to have 284px on right padding. It also looks like the padding on top and bottom make the height of each accordion item too tall.
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/111377779/234388032-c31149fb-c897-45a5-94d8-83d6b7df733c.png">

**Comment by sachinmesh** [comment]
Adding my observations with attached PDF

[Zelta Event page QA v1 (1).pdf](https://github.com/hlxsites/merative/files/11333536/Zelta.Event.page.QA.v1.1.pdf)


CC: @keith-kaplan @anabarcelona

**Comment by keith-kaplan** [comment]
Clarification on this one. For the event leadspace, we want to make sure the html tag is still an H1 tag vs an H2 tag. I think Sachin mentioned the style/typography on the heading and not the tag.

**Comment by arumsey** [comment]
Most of your issues have been addressed here: https://182-events-qa--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference (@keith-kaplan @sachinmesh).

One outstanding issue is the spacing between Marketo form labels and fields. There is some custom CSS being delivered with the Marketo form that forces the label padding to be 12px. This custom CSS provided by Marketo has a higher importance that the Franklin CSS which is why we cannot change it to 16px. You should be able to add extra px from the Marketo side potentially.

**Comment by arumsey** [comment]
@sachinmesh & @keith-kaplan The events pages are ready for review again.

**Comment by sachinmesh** [comment]
Hi Team, 
Sharing the review here in PDF. Also, issues which are pending are mentioned  below.

[Zelta Event page QA v2.pdf](https://github.com/hlxsites/merative/files/11352335/Zelta.Event.page.QA.v2.pdf)


**Leadspace** 
Heading font style should be H2 – Source serif pro 45px light, for event leadspace only. - Not Fixed 

**Content band list** 
The spacing between title and 3 icons list should be 48px. - Not Fixed 

**Simple content component**
Title and body text should be 32px. - Not Fixed 
Padding above and below should be 160px. - Not Fixed 

**Form component** 
Submit CTA should have 48px spacing above.  - Not Fixed

CC: @keith-kaplan @anabarcelona

**Comment by arumsey** [comment]
> Leadspace
> Heading font style should be H2 – Source serif pro 45px light, for event leadspace only. - Not Fixed

@sachinmesh  I am seeing `Source Serif Pro Light` and `45px`. What are you getting?

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1004204/235155174-5dc318b4-f95d-4e82-bd7e-190ac282341d.png">

**Comment by arumsey** [comment]
> Content band list
The spacing between title and 3 icons list should be 48px. - Not Fixed

@sachinmesh I am seeing `32px + 16px = 48px` spacing between title and three icons. What are you getting?

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1004204/235155957-d7603ea4-9bb1-4196-af52-817ef539875b.png">

<img width="770" alt="image" src="https://user-images.githubusercontent.com/1004204/235156337-959cd49b-f05d-4561-86dc-d2bf5795039b.png">

**Comment by arumsey** [comment]
> Simple content component

- Title and body text should be 32px. **FIXED**

<img width="609" alt="image" src="https://user-images.githubusercontent.com/1004204/235158483-b5ef06fb-43f3-4bdb-8bda-9672bef2e90f.png">

-  Padding above and below should be 160px. - Not Fixed

@sachinmesh Where are you expecting to see the `160px` padding? Currently there is `160px` padding at the top and bottom of the sectino that contains all the simple content blocks.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/1004204/235158886-c52e12c4-97a6-4a51-98f7-ee6475547a05.png">


<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1004204/235158985-b28acce4-2e01-4899-8bef-87219827c3c7.png">

**Comment by arumsey** [comment]
> Form component
Submit CTA should have 48px spacing above. **FIXED**

I had to fight with styles coming form Marketo but all the extra margins should be removed now resulting in an actual `48px` gap between form content and Submit button.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1004204/235160574-23376704-2521-4f7f-9cfa-a32e02f552d2.png">

**Comment by sachinmesh** [comment]
Hi, 
This is the link i was checking https://main--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference

This link is showing 404 error https://182-events-qa--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference

CC: @keith-kaplan @anabarcelona

**Comment by arumsey** [comment]
> Hi, This is the link i was checking https://main--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference
> 
> This link is showing 404 error https://182-events-qa--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference
> 
> CC: @keith-kaplan @anabarcelona

https://182-events-qa--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference has been merged.

Can you please elaborate on the following oustanding questions using https://main--merative2--hlxsites.hlx.page/events/2023-zelta-user-conference.

- [Heading font style should be H2 – Source serif pro 45px light, for event leadspace only](https://github.com/hlxsites/merative/issues/182#issuecomment-1527536772). (Leadspace heading font size is already 45px)
- [The spacing between title and 3 icons list should be 48px](https://github.com/hlxsites/merative/issues/182#issuecomment-1527542124) (Margin between title and content-band icons is already 48px)
- [Padding above and below should be 160px](https://github.com/hlxsites/merative/issues/182#issuecomment-1527557146) (Padding above and below the simple content section is already 160px)

If you are still encountering these issues please provide screenshots on what you are seeing in your browser.

@sachinmesh

**Comment by sachinmesh** [comment]
Hi,

<img width="578" alt="image" src="https://user-images.githubusercontent.com/124026684/235707406-71b8f420-f49b-4ad3-88e1-1f8725017c58.png">

Here the title Zelta User conference is showing H1 is fixed now.






<img width="1075" alt="image" src="https://user-images.githubusercontent.com/124026684/235708158-dd19c892-3382-464a-940c-392106ddced1.png">

Here the padding shows 32px, **it should be 48px.**







<img width="1174" alt="image" src="https://user-images.githubusercontent.com/124026684/235708527-19632911-837e-41a3-84f7-65a58d80acfe.png">

The spacing between each quarter circle components **should have 160px above and below.** like this in design



<img width="754" alt="image" src="https://user-images.githubusercontent.com/124026684/235708889-f4863849-99a0-4d7d-b238-f47a6bf7dea8.png">


CC: @keith-kaplan @anabarcelona

**Comment by keith-kaplan** [comment]
@sachinmesh  It should be 96px between the "learn" blocks. not 160px. 

@arumsey  I'm seeing 96px so it should be good.

**Comment by arumsey** [comment]
> Here the padding shows 32px, **it should be 48px.**

@sachinmesh Please refer to https://github.com/hlxsites/merative/issues/182#issuecomment-1527542124

There is an additional `16px` margin above the icons resulting in a total of `48px`.

**Comment by sachinmesh** [comment]
Looks good. Thank you.
